language: node_js
node_js:
  - 10

notifications:
  email: false
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - npm run build

script:
  - npm run test