version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:9
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: 
          name: "Install dependencies"
          command: npm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: .
          paths: .
  build: 
    docker:
      - image: circleci/node:9
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run:
          name: "Build Project"
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  jest:
    docker:
      - image: circleci/node:9
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: 
          name: "Jest Test"
          command: yarn jest -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - persist_to_workspace:
          root: .
          paths: .
  cypress:
    docker:
      - image: cypress/base:9
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: ls -la /
      - run: ls -la /root/.cache
      - run:
          name: Cypress tests
          command: $(npm bin)/cypress run --config fileServerFolder=build --reporter mocha-multi-reporters --reporter-options configFile=cypress/reporters.json
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - persist_to_workspace:
          root: .
          paths: .
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - cypress:
          requires:
            - build


