version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8
        environment:
          TERM: xterm
    working_directory: /app
    steps:
      - checkout
      - attach_workspace:
          at: /app
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: 
          name: "Install dependencies"
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: /app
          paths: /app
  build: 
    docker:
      - image: circleci/node:8
        environment:
          TERM: xterm
    working_directory: /app
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn install
      - run:
          name: "Build Project"
          command: yarn build
      - persist_to_workspace:
          root: /app
          paths: /app
  jest:
    docker:
      - image: circleci/node:8
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: /app
      - run: yarn install
      - run: 
          name: "Jest Test"
          command: yarn jest -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - persist_to_workspace:
          root: /app
          paths: /app
  cypress:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: /app
      - run: yarn install
      - run:
          name: Cypress tests
          command: npm run test:cypress -- --config fileServerFolder=build --reporter mocha-multi-reporters --reporter-options configFile=cypress/reporters.json
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - persist_to_workspace:
          root: /app
          paths: /app
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - jest:
          requires:
            - build
      - cypress:
          requires:
            - build


